string id
bool append
---
# 0: SUCCESS, 
# 1: SIMILAR_EMBEDDING_FOUND, 
# 2: SIMILAR_EMBEDDING_FOUND_WITH_DIFFERENT_ID,
# 3: ID_FOUND_WITH_DISTANT_EMBEDDING 
# 4: MULTIPLE_EMBEDDINGS_FOUND, 
# 5: NO_EMBEDDINGS_FOUND, 
# 6: ERROR
uint8 result
string message