name: Tag and Release on Version Bump

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Bump version to')

    outputs:
      new_tag: ${{ steps.extract.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get App Token
        id: app-token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Extract version from commit message
        id: extract
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create and push tag using app token
        run: |
          git config user.name "kyrikakis-release-bot[bot]"
          git config user.email "release-bot@users.noreply.github.com"
          git tag ${{ env.version }}
          git push https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }} ${{ env.version }}

  release:
    name: Release Image
    needs: tag
    uses: ./.github/workflows/release-image.yaml
    with:
      version: ${{ needs.tag.outputs.new_tag }}
