name: Tag and Release on Version Bump

on:
  push:
    branches:
      - test-tag

permissions:
  contents: write
  packages: write

jobs:
  tag:
    name: Create Git Tag
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Bump version to')

    outputs:
      new_tag: ${{ steps.extract.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from commit message
        id: extract
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ env.version }}
          git push origin ${{ env.version }}

  release:
    name: Release Image
    needs: tag
    uses: ./.github/workflows/release-image.yaml
    with:
      version: ${{ needs.tag.outputs.new_tag }}
